#!/bin/bash

mkdir ~/terminus
cd ~/terminus
curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install || exit 0
/home/runner/terminus/vendor/bin/terminus self:info
/home/runner/terminus/vendor/bin/terminus auth:login --machine-token="$MACHINETOKEN"
/home/runner/terminus/vendor/bin/terminus auth:login --email="$PANTHEONEMAIL"
/home/runner/terminus/vendor/bin/terminus auth:whoami